name: Run Social Auto Poster

on:
  # Does not work since we need to validate the device after Facebook login
  # schedule:
    # - cron: "*/5 * * * *"  # Every 5 minutes (for testing purpose)
    # - cron: "0 10 * * 2"  # Every Tuesday at 10:00 UTC (11:00 Belgium time)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Install clipboard tools
        run: sudo apt-get install -y xclip xsel
      
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run Selenium script with Xvfb
        run: xvfb-run -a python3 main.py
        env:
          POST_TEXT: ${{ secrets.POST_TEXT }}
          FACEBOOK_EMAIL: ${{ secrets.FACEBOOK_EMAIL }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
          DRY_RUN: "true"
          MAX_GROUPS: ""
