name: Run Social Auto Poster

# Automatic Run
on:
  schedule:
    - cron: "0 10 * * 2"  # Every Tuesday at 10:00 UTC (11:00 Belgium time)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver xvfb
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run Selenium script
        run: |
          export CHROME_BIN=$(which chromium-browser)
          export PATH=$PATH:$(dirname $(which chromedriver))
          python3 social-auto-poster.py
        env:
          POST_TEXT: ${{ secrets.POST_TEXT }}
          DRY_RUN: "false"
          MAX_GROUPS: ""
  